In [1]:
import bw2data as bd
import bw2calc as bc
bd.projects.set_current("exon")
bd.databases

Databases dictionary with 7 object(s):
	exiobase-3.8.2-2022-1e-3
	exiobase-3.8.2-2022-1e-4
	exiobase-3.8.2-2022-1e-5
	exiobase-3.8.2-2022-1e-6
	exiobase-3.8.2-2022-1e-7
	exiobase-3.8.2-2022-1e-8
	exiobase-3.8.2-and-less-biosphere

In [7]:
exio = bd.Database("exiobase-3.8.2-2022-1e-8")
act = [_ for _ in exio if _["name"]=='Gas Works Gas' and _["location"]=="RO"][0]
act

'Gas Works Gas' (euro, RO, None)

In [8]:
act.exchanges().to_dataframe()

,target_id,target_database,target_code,target_name,target_reference_product,target_location,target_unit,target_type,source_id,source_database,source_code,source_name,source_product,source_location,source_unit,source_categories,edge_amount,edge_type
0,297023450597326925,exiobase-3.8.2-2022-1e-8,e90d8d03-c095-4202-abae-22ec2d4947b2,Gas Works Gas,Gas Works Gas,RO,euro,processwithreferenceproduct,297023450597326925,exiobase-3.8.2-2022-1e-8,e90d8d03-c095-4202-abae-22ec2d4947b2,Gas Works Gas,NaN,RO,euro,NaN,1.0,production

In [10]:
import pandas as pd
from exon import DATA
a_file_path = DATA/"databases"/"exiobase"/"3.8.2"/"A.csv"
a = pd.read_csv(
                a_file_path, sep=",", low_memory=False, header=[0, 1], index_col=[0, 1]
            )
a

region                                                           AT  \
sector                                                   Paddy rice
region sector
AT     Paddy rice                                                 0
       Wheat                                                      0
       Cereal grains nec                                          0
       Vegetables, fruit, nuts                                    0
       Oil seeds                                                  0
...                                                             ...
WM     Membership organisation services n.e.c. (91)               0
       Recreational, cultural and sporting services (92)          0
       Other services (93)                                        0
       Private households with employed persons (95)              0
       Extra-territorial organizations and bodies                 0

region                                                                  \
sector                                                           Wheat
region sector
AT     Paddy rice                                         0.000000e+00
       Wheat                                              3.292837e-02
       Cereal grains nec                                  0.000000e+00
       Vegetables, fruit, nuts                            0.000000e+00
       Oil seeds                                          0.000000e+00
...                                                                ...
WM     Membership organisation services n.e.c. (91)       7.944217e-10
       Recreational, cultural and sporting services (92)  7.608218e-07
       Other services (93)                                7.067870e-08
       Private households with employed persons (95)      0.000000e+00
       Extra-territorial organizations and bodies         0.000000e+00

region                                                                      \
sector                                                   Cereal grains nec
region sector
AT     Paddy rice                                             0.000000e+00
       Wheat                                                  0.000000e+00
       Cereal grains nec                                      1.410620e-02
       Vegetables, fruit, nuts                                0.000000e+00
       Oil seeds                                              0.000000e+00
...                                                                    ...
WM     Membership organisation services n.e.c. (91)           7.018045e-10
       Recreational, cultural and sporting services (92)      6.763146e-07
       Other services (93)                                    6.242791e-08
       Private households with employed persons (95)          0.000000e+00
       Extra-territorial organizations and bodies             0.000000e+00

region                                                                            \
sector                                                   Vegetables, fruit, nuts
region sector
AT     Paddy rice                                                   0.000000e+00
       Wheat                                                        0.000000e+00
       Cereal grains nec                                            0.000000e+00
       Vegetables, fruit, nuts                                      7.266763e-02
       Oil seeds                                                    0.000000e+00
...                                                                          ...
WM     Membership organisation services n.e.c. (91)                 7.374026e-10
       Recreational, cultural and sporting services (92)            7.132512e-07
       Other services (93)                                          6.558172e-08
       Private households with employed persons (95)                0.000000e+00
       Extra-territorial organizations and bodies                   0.000000e+00

region                                                                  \
sector                                                       Oil seeds
region sector
AT     Paddy rice                                         0.000000e+00
       Wheat                                              0.000000e+00
       Cereal grains nec                                  0.000000e+00
       Vegetables, fruit, nuts                            0.000000e+00
       Oil seeds                                          3.149272e-03
...                                                                ...
WM     Membership organisation services n.e.c. (91)       4.243297e-10
       Recreational, cultural and sporting services (92)  3.972912e-07
       Other services (93)                                3.771539e-08
       Private households with employed persons (95)      0.000000e+00
       Extra-territorial organizations and bodies         0.000000e+00

region                                                                           \
sector                                                   Sugar cane, sugar beet
region sector
AT     Paddy rice                                                  0.000000e+00
       Wheat                                                       0.000000e+00
       Cereal grains nec                                           0.000000e+00
       Vegetables, fruit, nuts                                     0.000000e+00
       Oil seeds                                                   0.000000e+00
...                                                                         ...
WM     Membership organisation services n.e.c. (91)                8.144901e-10
       Recreational, cultural and sporting services (92)           7.583974e-07
       Other services (93)                                         7.243598e-08
       Private households with employed persons (95)               0.000000e+00
       Extra-territorial organizations and bodies                  0.000000e+00

region                                                                       \
sector                                                   Plant-based fibers
region sector
AT     Paddy rice                                                       0.0
       Wheat                                                            0.0
       Cereal grains nec                                                0.0
       Vegetables, fruit, nuts                                          0.0
       Oil seeds                                                        0.0
...                                                                     ...
WM     Membership organisation services n.e.c. (91)                     0.0
       Recreational, cultural and sporting services (92)                0.0
       Other services (93)                                              0.0
       Private households with employed persons (95)                    0.0
       Extra-territorial organizations and bodies                       0.0

region                                                                  \
sector                                                       Crops nec
region sector
AT     Paddy rice                                         0.000000e+00
       Wheat                                              2.845494e-03
       Cereal grains nec                                  3.817136e-03
       Vegetables, fruit, nuts                            0.000000e+00
       Oil seeds                                          0.000000e+00
...                                                                ...
WM     Membership organisation services n.e.c. (91)       7.702721e-10
       Recreational, cultural and sporting services (92)  7.372396e-07
       Other services (93)                                6.853177e-08
       Private households with employed persons (95)      0.000000e+00
       Extra-territorial organizations and bodies         0.000000e+00

region                                                                  \
sector                                                          Cattle
region sector
AT     Paddy rice                                         0.000000e+00
       Wheat                                              5.090750e-03
       Cereal grains nec                                  2.950346e-02
       Vegetables, fruit, nuts                            1.789994e-04
       Oil seeds                                          0.000000e+00
...                                                                ...
WM     Membership organisation services n.e.c. (91)       1.433475e-09
       Recreational, cultural and sporting services (92)  1.391893e-06
       Other services (93)                                1.276494e-07
       Private households with employed persons (95)      0.000000e+00
       Extra-territorial organizations and bodies         0.000000e+00

region                                                                  ...  \
sector                                                            Pigs  ...
region sector                                                           ...
AT     Paddy rice                                         0.000000e+00  ...
       Wheat                                              4.421246e-03  ...
       Cereal grains nec                                  3.291875e-02  ...
       Vegetables, fruit, nuts                            6.330385e-04  ...
       Oil seeds                                          0.000000e+00  ...
...                                                                ...  ...
WM     Membership organisation services n.e.c. (91)       1.208689e-09  ...
       Recreational, cultural and sporting services (92)  1.167935e-06  ...
       Other services (93)                                1.071815e-07  ...
       Private households with employed persons (95)      0.000000e+00  ...
       Extra-territorial organizations and bodies         0.000000e+00  ...

region                                                                              WM  \
sector                                                   Paper for treatment: landfill
region sector
AT     Paddy rice                                                         0.000000e+00
       Wheat                                                              9.327327e-08
       Cereal grains nec                                                  3.345848e-07
       Vegetables, fruit, nuts                                            1.148259e-06
       Oil seeds                                                          1.197801e-08
...                                                                                ...
WM     Membership organisation services n.e.c. (91)                       8.986902e-05
       Recreational, cultural and sporting services (92)                  2.122776e-04
       Other services (93)                                                1.779252e-04
       Private households with employed persons (95)                      4.869706e-05
       Extra-territorial organizations and bodies                         0.000000e+00

region                                                                                          \
sector                                                   Plastic waste for treatment: landfill
region sector
AT     Paddy rice                                                                 0.000000e+00
       Wheat                                                                      1.126917e-07
       Cereal grains nec                                                          3.985634e-07
       Vegetables, fruit, nuts                                                    1.197784e-06
       Oil seeds                                                                  1.045350e-08
...                                                                                        ...
WM     Membership organisation services n.e.c. (91)                               1.127047e-04
       Recreational, cultural and sporting services (92)                          2.868261e-04
       Other services (93)                                                        2.116582e-04
       Private households with employed persons (95)                              4.298543e-05
       Extra-territorial organizations and bodies                                 0.000000e+00

region                                                                                                        \
sector                                                   Inert/metal/hazardous waste for treatment: landfill
region sector
AT     Paddy rice                                                                              0.000000e+00
       Wheat                                                                                   8.544947e-08
       Cereal grains nec                                                                       3.059879e-07
       Vegetables, fruit, nuts                                                                 1.064800e-06
       Oil seeds                                                                               1.123254e-08
...                                                                                                     ...
WM     Membership organisation services n.e.c. (91)                                            8.381961e-05
       Recreational, cultural and sporting services (92)                                       2.508701e-04
       Other services (93)                                                                     2.036235e-04
       Private households with employed persons (95)                                           3.958145e-05
       Extra-territorial organizations and bodies                                              0.000000e+00

region                                                                                           \
sector                                                   Textiles waste for treatment: landfill
region sector
AT     Paddy rice                                                                  0.000000e+00
       Wheat                                                                       7.206936e-08
       Cereal grains nec                                                           2.453986e-07
       Vegetables, fruit, nuts                                                     3.868300e-07
       Oil seeds                                                                   1.117152e-09
...                                                                                         ...
WM     Membership organisation services n.e.c. (91)                                1.512357e-04
       Recreational, cultural and sporting services (92)                           3.027660e-04
       Other services (93)                                                         2.891197e-04
       Private households with employed persons (95)                               4.907531e-05
       Extra-territorial organizations and bodies                                  0.000000e+00

region                                                                                       \
sector                                                   Wood waste for treatment: landfill
region sector
AT     Paddy rice                                                              0.000000e+00
       Wheat                                                                   8.101356e-08
       Cereal grains nec                                                       2.752202e-07
       Vegetables, fruit, nuts                                                 6.210077e-07
       Oil seeds                                                               1.999995e-09
...                                                                                     ...
WM     Membership organisation services n.e.c. (91)                            1.343271e-04
       Recreational, cultural and sporting services (92)                       3.027435e-04
       Other services (93)                                                     2.720793e-04
       Private households with employed persons (95)                           4.174247e-05
       Extra-territorial organizations and bodies                              0.000000e+00

region                                                                                                 \
sector                                                   Membership organisation services n.e.c. (91)
region sector
AT     Paddy rice                                                                        0.000000e+00
       Wheat                                                                             8.939519e-09
       Cereal grains nec                                                                 3.214958e-08
       Vegetables, fruit, nuts                                                           9.584451e-08
       Oil seeds                                                                         1.154877e-09
...                                                                                               ...
WM     Membership organisation services n.e.c. (91)                                      4.902650e-03
       Recreational, cultural and sporting services (92)                                 7.679166e-03
       Other services (93)                                                               3.451325e-03
       Private households with employed persons (95)                                     1.998597e-04
       Extra-territorial organizations and bodies                                        0.000000e+00

region                                                                                                      \
sector                                                   Recreational, cultural and sporting services (92)
region sector
AT     Paddy rice                                                                             0.000000e+00
       Wheat                                                                                  6.146572e-09
       Cereal grains nec                                                                      8.660173e-08
       Vegetables, fruit, nuts                                                                7.700667e-08
       Oil seeds                                                                              8.955088e-10
...                                                                                                    ...
WM     Membership organisation services n.e.c. (91)                                           1.932541e-03
       Recreational, cultural and sporting services (92)                                      6.783881e-02
       Other services (93)                                                                    3.501543e-03
       Private households with employed persons (95)                                          1.677406e-04
       Extra-territorial organizations and bodies                                             0.000000e+00

region                                                                        \
sector                                                   Other services (93)
region sector
AT     Paddy rice                                               0.000000e+00
       Wheat                                                    2.596816e-08
       Cereal grains nec                                        2.155794e-07
       Vegetables, fruit, nuts                                  4.334933e-07
       Oil seeds                                                4.472215e-09
...                                                                      ...
WM     Membership organisation services n.e.c. (91)             8.515677e-04
       Recreational, cultural and sporting services (92)        6.034577e-03
       Other services (93)                                      1.432397e-02
       Private households with employed persons (95)            3.523855e-04
       Extra-territorial organizations and bodies               0.000000e+00


In [14]:
weird_act = a.loc[:, ("RO", "Gas Works Gas")]
weird_act[weird_act !=0]

Series([], Name: (RO, Gas Works Gas), dtype: int64)

In [11]:
method = bd.methods.random()
method

('IMPACT World+ v2.2.1 for exiobase v3.8.2_and_before',
 'Midpoint',
 'Freshwater eutrophication (kg PO4 P-lim eq)')

In [12]:
my_lca = bc.LCA({act:1}, method=method)
my_lca.lci()
my_lca.lcia()
my_lca.score

:

:

In [ ]:
new_method=bd.methods.random()
new_method

('IMPACT World+ v2.2.1 for exiobase v3.8.2_and_before',
 'Ecosystem Quality',
 'Marine eutrophication (PDF.m2.yr)')

In [ ]:
my_lca = bc.LCA({act:1}, method=new_method)
my_lca.lci()
my_lca.lcia()
my_lca.score

0.0940675844074741